package io.nebula.common.event;

public interface EventTag {
    String ENGINE_ONLINE_BEFORE = "ENGINE_ONLINE_BEFORE";
    String ENGINE_OFFLINE_BEFORE = "ENGINE_OFFLINE_BEFORE";
    String ENGINE_ONLINE = "ENGINE_ONLINE";
    String ENGINE_OFFLINE = "ENGINE_OFFLINE";
    String ENGINE_OFFLINE_CLEAR = "ENGINE_OFFLINE_CLEAR";

    String GAME_BEFORE_JOIN_CHECK = "GAME_BEFORE_JOIN_CHECK";
    String GAME_ROOM_INFO = "GAME_ROOM_INFO";
    String GAME_ROOM_CREATED_INIT = "GAME_ROOM_CREATED_INIT";
    String GAME_ROOM_TIMER = "GAME_ROOM_TIMER";
    String GAME_BEFORE_READY_CHECK = "GAME_BEFORE_READY_CHECK";
    String PLAYER_ELIMINATE_LEAVE = "PLAYER_ELIMINATE_LEAVE";
    String GAME_AFTER_CALCULATE_SYNC = "GAME_AFTER_CALCULATE_SYNC";
    String GAME_SOMEONE_READY = "GAME_SOMEONE_READY";
    String GAME_OFFLINE_LEAVE_CHECK = "GAME_OFFLINE_LEAVE_CHECK";
    String ENGINE_SOMEONE_EXIT_ROOM_SUCCESS = "ENGINE_SOMEONE_EXIT_ROOM_SUCCESS";
    String ENGINE_SOMEONE_JOIN_ROOM_SUCCESS = "ENGINE_SOMEONE_JOIN_ROOM_SUCCESS";
    String GAME_SOMEONE_EXIT_ROOM_SUCCESS = "GAME_SOMEONE_EXIT_ROOM_SUCCESS";
    String GAME_SOMEONE_JOIN_ROOM_SUCCESS = "GAME_SOMEONE_JOIN_ROOM_SUCCESS";
}
